<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Schema;

/**
 * Writes docs/db_schema.md: the whole database in one file, for humans and for the coding
 * agent that has no way to run a query.
 *
 * The column that matters most here is Comment. Every migration in this project is
 * required to give every column a ->comment() explaining what it holds and in what unit —
 * and for a long time the generator printed everything EXCEPT those comments, so the
 * strictest rule in the codebase produced documentation nobody could read. If you change
 * this command, keep the comments.
 */
class GenerateDbSchemaMarkdown extends Command
{
    protected $signature = 'schema:markdown';

    protected $description = 'Write docs/db_schema.md — a map of the database, column comments included';

    /**
     * Framework plumbing. Documenting it costs context and tells nobody anything.
     */
    private const SKIP_TABLES = [
        'migrations',
        'jobs',
        'job_batches',
        'failed_jobs',
        'cache',
        'cache_locks',
        'sessions',
        'password_reset_tokens',
    ];

    public function handle(): int
    {
        $lines = [
            '# Database schema',
            '',
            '> Generated by `php artisan schema:markdown`. Do not edit by hand — regenerate it',
            '> after every migration, and commit the result together with the migration.',
            '',
        ];

        $undocumented = [];
        $documented = 0;

        foreach (Schema::getTables() as $table) {
            // Postgres reports tables schema-qualified ("public.cache"), so comparing the
            // qualified string against a skip list of bare names silently matches nothing
            // and the whole filter becomes decorative. Filter on ['name'], read columns
            // through ['schema_qualified_name'] — that one is unambiguous across schemas.
            $name = $table['name'];

            if (in_array($name, self::SKIP_TABLES, true)) {
                continue;
            }

            $lines[] = "## `{$name}`";
            $lines[] = '';

            if (! empty($table['comment'])) {
                $lines[] = '_'.$this->cell($table['comment']).'_';
                $lines[] = '';
            }

            $lines[] = '| Column | Type | Nullable | Default | Comment |';
            $lines[] = '|---|---|---|---|---|';

            foreach (Schema::getColumns($table['schema_qualified_name'] ?? $name) as $column) {
                $comment = (string) ($column['comment'] ?? '');

                if ($comment === '') {
                    $undocumented[] = "{$name}.{$column['name']}";
                } else {
                    $documented++;
                }

                $lines[] = sprintf(
                    '| `%s` | `%s` | %s | %s | %s |',
                    $column['name'],
                    $column['type_name'],
                    $column['nullable'] ? 'yes' : 'no',
                    $column['default'] === null ? '—' : '`'.$this->cell((string) $column['default']).'`',
                    $this->cell($comment),
                );
            }

            $lines[] = '';
        }

        if (! is_dir($docs = base_path('docs'))) {
            mkdir($docs, 0o755, true);
        }

        file_put_contents($docs.'/db_schema.md', implode("\n", $lines));

        $this->info('docs/db_schema.md updated.');

        // The point of the rule is that this list stays empty.
        if ($undocumented !== []) {
            $this->warn(sprintf(
                '%d of %d columns have no ->comment(): %s',
                count($undocumented),
                count($undocumented) + $documented,
                implode(', ', array_slice($undocumented, 0, 15)).(count($undocumented) > 15 ? ', …' : ''),
            ));
        }

        return self::SUCCESS;
    }

    /** Markdown tables end at the first raw pipe or newline. */
    private function cell(string $value): string
    {
        return str_replace(['|', "\n", "\r"], ['\|', ' ', ''], $value);
    }
}
