<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class GenerateDbSchemaMarkdown extends Command
{
    protected $signature = 'schema:markdown';
    protected $description = 'Generate docs/db_schema.md containing a bird\'s-eye view of the database schema for the AI.';

    public function handle()
    {
        $this->info('Generating Database Schema Markdown...');

        $tables = Schema::getTableListing();
        $output = "# Database Schema Map\n\n> This file is auto-generated by `php artisan schema:markdown`. Do not edit manually.\n\n";

        foreach ($tables as $table) {
            if (in_array($table, ['migrations', 'jobs', 'cache', 'cache_locks', 'failed_jobs', 'job_batches'])) {
                continue; // Skip system tables to save context window
            }

            $output .= "## Table: `{$table}`\n\n";
            $columns = Schema::getColumns($table);
            
            $output .= "| Column | Type | Nullable | Default |\n";
            $output .= "|--------|------|----------|---------|\n";

            foreach ($columns as $column) {
                $nullable = $column['nullable'] ? 'Yes' : 'No';
                $default = $column['default'] ?? 'NULL';
                $output .= "| `{$column['name']}` | `{$column['type_name']}` | {$nullable} | {$default} |\n";
            }
            $output .= "\n";
        }

        $docsPath = base_path('docs');
        if (!is_dir($docsPath)) {
            mkdir($docsPath, 0755, true);
        }

        file_put_contents($docsPath . '/db_schema.md', $output);

        $this->info('Schema map written to docs/db_schema.md');
    }
}
