<?php

namespace App\Console\Commands;

use App\Support\PermissionRegistry;
use Illuminate\Console\Command;

/**
 * Writes docs/permissions.md from App\Support\PermissionRegistry — the same idea as
 * schema:markdown, applied to access control: one generated page anyone (or any agent)
 * can read instead of piecing the matrix together from seeder code.
 *
 * What it prints is the DEFAULTS — who receives a permission at the moment it is first
 * created. The live matrix is in the database and is edited from the admin panel; the
 * seeder never re-syncs an existing link, so this file describes birth, not current state.
 */
class GeneratePermissionsMarkdown extends Command
{
    protected $signature = 'permissions:markdown';

    protected $description = 'Write docs/permissions.md from the PermissionRegistry';

    public function handle(): int
    {
        $lines = [
            '# Permissions',
            '',
            '> Generated by `php artisan permissions:markdown` from `App\Support\PermissionRegistry`.',
            '> Do not edit by hand — regenerate and commit it whenever the registry changes.',
            '',
            'The table below lists the roles a permission is granted to **when it is first',
            'created**. From then on the database is the truth: the access matrix is edited in',
            'the admin panel, and the seeder is additive only, so those edits survive deploys.',
            '',
            '## Adding a permission',
            '',
            '1. Add a case to `App\Enums\PermissionName`.',
            '2. Add an entry to `App\Support\PermissionRegistry` (description + default roles).',
            '3. Deploy: `RolesAndPermissionsSeeder` creates it and links the default roles.',
            '4. Run `php artisan permissions:markdown` and commit this file.',
            '5. Enforce it: `$user->can(...)` or the `permission:` middleware on the route.',
            '',
            '## Permissions',
            '',
            '| Permission | What it allows | Default roles |',
            '|---|---|---|',
        ];

        foreach (PermissionRegistry::all() as $permission => $definition) {
            $lines[] = sprintf(
                '| `%s` | %s | %s |',
                $permission,
                $definition['description'],
                '`'.implode('`, `', PermissionRegistry::defaultRolesFor($permission)).'`',
            );
        }

        $lines[] = '';
        $lines[] = '## Roles';
        $lines[] = '';
        $lines[] = '`'.implode('`, `', PermissionRegistry::ROLES).'` — `admin` holds every permission by';
        $lines[] = 'definition, which is what keeps an administrator from locking themselves out of the';
        $lines[] = 'screen where permissions are edited.';
        $lines[] = '';

        if (! is_dir($docs = base_path('docs'))) {
            mkdir($docs, 0o755, true);
        }

        file_put_contents($docs.'/permissions.md', implode("\n", $lines));

        $this->info('docs/permissions.md updated.');

        return self::SUCCESS;
    }
}
