<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Storage for the `database` notification channel.
 *
 * Present from the start on purpose: the admin panel enables its notification
 * bell (->databaseNotifications()) and every page of the panel throws as soon
 * as it queries a table that does not exist.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('notifications', function (Blueprint $table) {
            $table->uuid('id')->primary()->comment('Notification UUID, generated by the framework');
            $table->string('type')->comment('Notification class that produced this row');
            $table->string('notifiable_type')->comment('Model class the notification is addressed to');
            $table->unsignedBigInteger('notifiable_id')->comment('Id of that model; polymorphic, so no foreign key');
            $table->text('data')->comment('JSON payload returned by the notification toArray()/toDatabase()');
            $table->timestamp('read_at')->nullable()->comment('When the recipient read it; null = unread');
            $table->timestamp('created_at')->nullable()->comment('Delivery timestamp');
            $table->timestamp('updated_at')->nullable()->comment('Last modification timestamp');

            $table->index(['notifiable_type', 'notifiable_id']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('notifications');
    }
};
